### PR TITLE
feat/ added a route to change url, to avoid restarting the app and ch…

### PR DESCRIPTION
**Pull request by jgengo**
Hello!

I proposed this Pull request, regarding the fact you need to change your Heroku ENV variable and restarting your app every time your ngrok address change.

I added a route /update_ngrok protected with a key you have to specify in your Heroku ENV

It allows you to change your URL by just getting the page: `https://HEROKU_URL/update_ngrok&secret=SECRET&url=NGROK_URL`, either by your browser or a simple curl.

I also edit a little bit of your README to mention this feature.

### CODE REVIEW

**Review by urbanishimwe — APPROVED** [review]
LGTM!

**Comment by urbanishimwe** [comment]
> Hello!
> 
> I proposed this Pull request, regarding the fact you need to change your Heroku ENV variable and restarting your app every time your ngrok address change.
> 
> I added a route /update_ngrok protected with a key you have to specify in your Heroku ENV
> 
> It allows you to change your URL by just getting the page: `https://HEROKU_URL/update_ngrok&secret=SECRET&url=NGROK_URL`, either by your browser or a simple curl.
> 
> I also edit a little bit of your README to mention this feature.

Than

**Review by urbanishimwe — COMMENTED** [review]
Thanks, @jgengo really cool improvements

**Comment by jgengo** [comment]
👍

**Pull request merged**
